## 8.1异常

### try... catch语句

```java
try{

}catch(){

}
```

捕捉异常的大致流程：

![image-20201201221829141](8.异常处理与输入输出.assets/image-20201201221829141.png)

### 再度抛出异常用throw语句

```java
catch(Exception e){

System.err.println("An exception was thrown");

throw e;

}


```

如果在这个层面上需要处理，但不能做最终的决定

## 8.2异常机制

### 用上异常机制

```java
try{
    open the file;//打开文件
    determine its size;//判断文件的大小
    allocate that much memory;//分配足够的内存空间
    read the file into memory;//把文件读入内存空间
    close the file;//关闭文件
}catch(fileOpenFailed){
   doSomething;
}catch(sizeDeterminationFailed){
doSomething;
}catch(memoryAllocationFailed){
doSomething;
}catch(fileCloseFailed){
doSomething;
}
```

### 异常

有不同寻常的事发生了

当这个事情发生的时候，原本要打算接着做的事情不能再继续了，必须得要停下来，让其他地方的某段代码来处理.

**异常机制最大的好处就是：**

**清晰的分开了正常的业务逻辑代码和遇到情况时的处理代码**

```java


class OpenException extends Throwable{   	

}//如果出现这种异常需要在这里声明OpenException是Throwable的子类，因为在下面抛出的异常必须是Throwable类型的
//即an exception type must be a subclass of Throwable 

class CloseException extends Throwable{
	
}//同上

public class ArrayIndex {
    public static int open() {
    	return -1;
    }
    
    public static void readFile() throws OpenException,CloseException {  //如果函数可能会抛出异常就要在这里声明
    	if(open()==-1) {
    		throw new OpenException();
    	}
    }
    
	public static void main(String[] args) {
        try {
			readFile();
		} catch (OpenException e) {
			e.printStackTrace();
		} catch (CloseException e) {
			e.printStackTrace();
		}
	}

}

```

### 什么能扔？

任何继承了Throwable类的对象

Exception类继承了Throwable

  有两种形式：

​       `throw new Exception();`

​     `throw new Exception("HELP");` 

### catch怎么匹配异常的

异常类`Throwable`  是所有异常类的父类，`Exception`类可以捕捉到任何的异常，但它不能像`Throwable`一样直接将声明的异常覆盖.